In [1]:
import sys
sys.executable

'/u/home/systems/dauria/.conda/envs/mycondatf/bin/python'

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-12-06 09:24:41.885368: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-06 09:24:41.946265: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-06 09:24:41.946304: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-06 09:24:41.947105: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-06 09:24:41.953218: I tensorflow/core/platform/cpu_feature_guar

TensorFlow version: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-12-06 09:25:20.324529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79087 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:01:00.0, compute capability: 8.0


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

2023-12-06 09:25:30.710531: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

2023-12-06 09:25:30.738905: W external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:225] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.0
2023-12-06 09:25:30.738949: W external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:228] Used ptxas at ptxas
2023-12-06 09:25:30.739021: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:191] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.


array([[-0.42482442,  0.11560956,  0.43776968, -0.18343848, -0.11929533,
        -0.81262153,  0.33542088, -0.9218505 ,  0.3055199 ,  0.08191636]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.06721441, 0.11539046, 0.15925103, 0.08556477, 0.09123301,
        0.04560834, 0.14375824, 0.04088902, 0.13952336, 0.11156736]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

3.0876646

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-12-06 09:27:22.747206: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

2023-12-06 09:27:22.748785: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

2023-12-06 09:27:22.748854: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

2023-12-06 09:27:22.765799: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.

  26/1875 [..............................] - ETA: 3s - loss: 1.6907 - accuracy: 0.5084     

2023-12-06 09:27:24.405833: E external/local_xla/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.2.89, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.



1875/1875 [==============================] - 6s 2ms/step - loss: 0.2995 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1457 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1096 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0887 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0781 - accuracy: 0.9756


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0748 - accuracy: 0.9784 - 478ms/epoch - 2ms/step


[0.0748196691274643, 0.9783999919891357]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.0622417e-07, 2.9500507e-08, 5.3450322e-06, 4.1243282e-05,
        2.3850058e-10, 4.9401251e-07, 2.7111074e-12, 9.9994016e-01,
        7.2165363e-07, 1.1776370e-05],
       [8.8108493e-08, 1.1432504e-03, 9.9881697e-01, 3.9178551e-05,
        1.6756669e-15, 1.8932018e-07, 2.3544697e-09, 1.4560906e-13,
        3.0287777e-07, 7.6463805e-14],
       [2.5602990e-06, 9.9901700e-01, 4.0372553e-05, 5.6280784e-05,
        7.9813733e-05, 1.4715853e-05, 2.6682008e-05, 3.6021127e-04,
        3.9947112e-04, 2.9205310e-06],
       [9.9947494e-01, 3.3785234e-08, 4.7580092e-05, 1.9441021e-07,
        6.1524850e-07, 1.7989352e-05, 1.6350535e-04, 2.5943300e-04,
        1.9411663e-08, 3.5667901e-05],
       [1.9017067e-05, 1.6210137e-08, 4.0561904e-06, 5.0059737e-07,
        9.8346484e-01, 4.0247457e-07, 6.6227869e-07, 4.3281220e-04,
        1.1848907e-06, 1.6076662e-02]], dtype=float32)>